version: '3.8'

services:
  backend:
    container_name: todolist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db  # db 서비스 이름 사용
      - DB_PORT=3308
      - DB_USER=root
      - DB_PASSWORD=1111
      - DB_NAME=todolist
    depends_on:
      - db  # backend는 db 서비스가 먼저 실행되어야 함

  frontend:
    container_name: todolist-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    container_name: todolist-db
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: todolist
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
